### PR TITLE
Add an appdata entry

### PR DESCRIPTION
**Pull request by keszybz**
https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps

This is motivated by Fedora packaging, but is generally useful also for other Linux distributions. Feel free to improve the descriptions and images — I have never used your software before, so the screenshots I made are all rather simplistic.

### CODE REVIEW

**Comment by keszybz** [comment]
Oops, I see #5 was filed 20 minutes ago.

**Comment by eclipseo** [comment]
Hi dear sponsor, sorry :D

**Comment by AdelKS** [comment]
Hey,

Thank you for your help! 

There are screen-shots and a complete description  in [ZeGrapher's  website](zegrapher.com), I'll update the folder with those.

**Comment by keszybz** [comment]
There's an issue that appdata screenshots should be 16:9, and preferably from a modern Linux desktop environment. So most screenshots don't fit too well.

**Comment by AdelKS** [comment]
Oh I see, 16:9 copy that. Can I add more pictures or is there a limit ?

The screenshots that are in the website have been taken from a modern Linux desktop, but it is true that I changed the style of the widgets...

**Comment by keszybz** [comment]
I don't think there a strict limit on the number of screenshots. gnome-software has a space for at least 5 thumbnails. I don't know what happens when you have more screenshots than that.

One thing I forgot to mention: I put my screenshots under my homepage. It's not going away anytime soon or anything like that, but in the long run you probably should move update the URLs to github repo or to the place where documentation is hosted.

**Pull request merged**
